### PR TITLE
chore: update deno.json to top level exclude

### PR DESCRIPTION
**Pull request by sigmaSd**

### CODE REVIEW

**Comment by dsherret** [comment]
Very weird that it's pulling in the wrong version.

**Comment by sigmaSd** [comment]
yeah weird can't reproduce locally, with setup-deno it finds the correct version

**Comment by sigmaSd** [comment]
My only guess is that maybe the ci has some old cached version of https://deno.com/versions.json

**Comment by dsherret** [comment]
We figured it out. It was pinned to v1.0.0

**Comment by sigmaSd** [comment]
oh xD I thought I checked that

**Pull request merged**
