### PR TITLE
chore: publish to JSR in GitHub Actions

### PR DESCRIPTION
**Pull request by iuioiua**

### CODE REVIEW

**Review by dsherret — COMMENTED** [review]
It's already doing this. It looks like the publish just failed due to the CI creating changes.

**Comment by dsherret** [comment]
I'll submit a fix.

**Comment by iuioiua** [comment]
Yeah, haha. I saw how this is set up right after submitting the PR. Why use a setup script instead of just setting the `version` field in `deno.json`?

**Comment by iuioiua** [comment]
Closing in favour of #133.

**Pull request closed without merging**
