### PR TITLE
feat: generate wasm caching helper

### LINKED ISSUE #23: Separate out re-usable generated code into separate module
From #22:

> Are there any optimizations that would enable the multiple builds to share some of the env glue? Each of these will bundle in the allocator... this isn't ideal. Any tips would be greatly appreciated.

Not sure how easy this would be, but it would be nicer because it would allow re-using a bunch of boilerplate code. Perhaps it could even import this module from deno.land/x/wasmbuild to reduce the amount of noise in a repo.

### LINKED ISSUE #67: Add wasm file caching
https://github.com/dsherret/dax/issues/44#issuecomment-1366422313

Either wasmbuild handle this , or have an option to generate code that does, but it needs to stay compatible with the browser so I guess we can't use modules like https://deno.land/x/cache@0.2.13

We can take inspiration from [dax](https://github.com/dsherret/dax/blob/760f04dc12354e1691efea9d47eececbefd96f42/src/lib/mod.ts#L27)

### PR DESCRIPTION
**Pull request by sigmaSd**
Closes #67
Closes #23

### CODE REVIEW

**Comment by sigmaSd** [comment]
The file is based on your implementation just 2 differences mentioned above

**Comment by sigmaSd** [comment]
Another option is just to keep the file in the repo and point to it in the docs

**Comment by littledivy** [comment]
I'm in favour. (I need caching in deno_swc) 

WDYT @dsherret?

**Comment by dsherret** [comment]
I'd like this, but I think we should try to generate it without any external dependencies. It looks like we don't need them.

**Review by dsherret — APPROVED** [review]
LGTM! I've reworked this so that the user doesn't need to manage this code and it's automatically generated when building. Hopefully it works once published.

**Comment by sigmaSd** [comment]
Nice thanks for this, really useful

**Pull request merged**
