### PR TITLE
fix: use CARGO_ENCODED_RUSTFLAGS instead of RUSTFLAGS to pass flags to rustc

### LINKED ISSUE #98: wasmbuild task can fail if current folder contains a whitespace
Hi there,
reproducing this issue is quite simple: if the path of the project contains any whitespace, then wasmbuild fails.
As an example take this project, created in a folder named "wasmbuild bug":
```
$ deno task wasmbuild
Task wasmbuild deno run -A https://deno.land/x/wasmbuild@0.15.0/main.ts
Ensuring wasm32-unknown-unknown target installed...
Building rs_lib WebAssembly...
  build --lib -p rs_lib --target wasm32-unknown-unknown --release
error: failed to run `rustc` to learn about target-specific information

Caused by:
  process didn't exit successfully: `/Users/fc/.rustup/toolchains/stable-aarch64-apple-darwin/bin/rustc - --crate-name ___ --print=file-names --remap-path-prefix=/Users/fc/projects/wasmbuild bug=. '--remap-path-prefix=/Users/fc=~' --target wasm32-unknown-unknown --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=split-debuginfo --print=crate-name --print=cfg` (exit status: 1)
  --- stderr
  error: --remap-path-prefix must contain '=' between FROM and TO

cargo build failed
```

I think the issue arises from the fact that the variable passed to `--remap-path-prefix=...` is not quoted.

### LINKED ISSUE #135: --remap-path-prefix arguments might be encoded incorrectly in RUSTFLAGS
:wave: Hello. I built the latest released version of \@std/crypto's wasm binary on my machine a few weeks ago. While looking at the data recently, I noticed that my local file paths were included in the wasm binary, which isn't supposed to be the case because we use `--remap-path-prefix` in `RUSTFLAGS` to replace local paths prefixes with something generic.

Comparing the current code setting RUSTFLAGS...
https://github.com/denoland/wasmbuild/blob/f89f6f3338bd74a52db7ac20596e6a79d5fb35e6/lib/pre_build.ts#L80-L81

...to an old version, back when the logic lived in a script in deno_std instead of this standalone tool...
https://github.com/denoland/deno_std/blob/7348d133a8011481e4ed76c6f84f3a4c7a51a844/_wasm_crypto/_build.ts#L44

...the only apparent difference is that the `'${root}'` and `'${home}'` are wrapped in single-quotes. I'm not sure how those are handled, but when I removed the single quotes in a local version of wasmbuild and rebuilt the \@std/crypto wasm binary, the paths were again remapped as I expected.

before:

```
$ strings target/wasm32-unknown-unknown/release/deno_std_wasm_crypto.wasm | grep cargo

ArrayVec: capacity exceeded in extend/from_iter/home/jeremy/.cargo/registry/src/index.crates.io-6f17d22bba15001f/blake3-1.5.1/src/lib.rs
[/home/jeremy/.cargo/registry/src/index.crates.io-6f17d22bba15001f/arrayvec-0.7.4/src/arrayvec.rs
/home/jeremy/.cargo/registry/src/index.crates.io-6f17d22bba15001f/keccak-0.1.5/src/lib.rsA round_count greater than KECCAK_F_ROUND_COUNT is not supported!
/home/jeremy/.cargo/registry/src/index.crates.io-6f17d22bba15001f/block-buffer-0.10.4/src/lib.rs:
```

after:

```
$ strings target/wasm32-unknown-unknown/release/deno_std_wasm_crypto.wasm | grep cargo

ArrayVec: capacity exceeded in extend/from_iter~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/blake3-1.5.1/src/lib.rs
[~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/arrayvec-0.7.4/src/arrayvec.rs
~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/keccak-0.1.5/src/lib.rsA round_count greater than KECCAK_F_ROUND_COUNT is not supported!
~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/block-buffer-0.10.4/src/lib.rs
```

I'm not sure why the quotes were added, so maybe this affects some other case, but if not perhaps it's worth removing them.

If they are required to handle paths which themselves contain `=` characters or something like that, I saw [a post on URLO](https://users.rust-lang.org/t/how-to-properly-use-remap-path-prefix/104406/6) suggesting a possible alternative, although I haven't tried this and am not sure exactly how it would be formatted:

> You can use `CARGO_ENCODED_RUSTFLAGS` instead which uses ASCII Unit Separator (`0x1f`) instead of space as argument separator. You can also use the new `--config` option to set the `build.rustflags` config to an array formatted as toml.

Thanks for reading.

### PR DESCRIPTION
**Pull request by jeremyBanks**
Use `CARGO_ENCODED_RUSTFLAGS` instead of `RUSTFLAGS` to pass flags to rustc, and fix incorrect quoting of our remapped path flags. This change allows arguments (including the ones added internally for `--remap-path-prefix`) to included space characters without causing errors.

If users of wasmbuild provide their own flags through `RUSTFLAGS`, they will be merged into our `CARGO_ENCODED_RUSTFLAGS` value, to match the existing behaviour of wasmbuild. If they provide flags through `CARGO_ENCODED_RUSTFLAGS`, those will take precedence and `RUSTFLAGS` will be ignored, in order to match [Cargo's precedence behaviour when both are specified](https://github.com/rust-lang/cargo/blob/07ac23a71c3005638ba7e9e43433f8db6963c9ba/src/cargo/core/compiler/build_context/target_info.rs#L744-L766).

(Note that because we're always passing rustc flags through the environment, Cargo invoked by wasmbuild will never use any flags that are specified in the project's own TOML files because the environment takes priority. This isn't a change of behaviour, I just wanted to note as a deviation from plain Cargo behaviour to make it clear that matching the environment variable precedence doesn't mean we're matching its overall precedence rules for flag configuration.)

---

fixes #98, tested by rebuilding wasmbuild's own wasm with the directory renamed `/mnt/c/Users/_/denoland/wasm= build`, to ensure that space characters and equals characters are both okay. (It's not possible to specify equals characters in the target path, by rustc's own logic, but in the source path they're handled correclty.)

fixes #135, tested by looking at the output of `strings target/wasm32-unknown-unknown/release/wasmbuild.wasm | grep cargo | head -n 10` which now includes `~/.cargo/` where it previously included `/home/jeremy/.cargo/`.

### CODE REVIEW

**Comment by jeremyBanks** [comment]
🦗

**Comment by dsherret** [comment]
> 🦗

I didn't see this PR until now. Just ask next time instead of crickets please. It's a Sunday night so I'll look at it later.

**Review by dsherret — APPROVED** [review]
LGTM. Thanks!

**Comment by jeremyBanks** [comment]
> > 🦗
> 
> I didn't see this PR until now. Just ask next time instead of crickets please. It's a Sunday night so I'll look at it later.

Apologies for the snark. Thanks for reviewing.

**Pull request merged**
